CREATE TABLE IF NOT EXISTS STUDENT (
  ROLL_NO TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE TEXT,
  AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
  ('1', 'CHRISTOPHER', 'BRUSSELS', '*****', 33),
  ('2', 'EMILY', 'PORT-LOUIS', '*****', 43),
  ('3', 'SHREYA', 'MONT-CHOISY', '*****', 14),
  ('4', 'HAILEY', 'VICTORIA', '*****', 11);

SELETCT * FROM STUDENT WHERE ADDRESS = MONT-CHOISY AND AGE=14;
SELETCT * FROM STUDENT WHERE ADDRESS = BRUSSELS OR AGE=22;
SELETCT * FROM STUDENT WHERE ADDRESS = VICTORIA AND AGE=6;
SELETCT * FROM STUDENT WHERE ADDRESS = PORT-LOUIS AND AGE=10;
